version: '3.8'

services:
  setup:
    build:
      context: infrastructure/docker/setup
    environment:
      PROTOCOL: ${PROTOCOL?}
      HTTP_PORT: ${HTTP_PORT?}
      HTTPS_PORT: ${HTTPS_PORT?}
      HOST: ${HOST?}
      ABS_PATH: ${ABS_PATH?}
      OWNER_CERT_PASSWORD: ${OWNER_CERT_PASSWORD?}
      SECRETARY_CERT_PASSWORD: ${SECRETARY_CERT_PASSWORD?}
      OWNER_GIVEN_NAME: ${OWNER_GIVEN_NAME?}
      OWNER_FAMILY_NAME: ${OWNER_FAMILY_NAME?}
      OWNER_ORGANIZATION: ${OWNER_ORGANIZATION?}
      OWNER_ORG_UNIT: ${OWNER_ORG_UNIT?}
      OWNER_LOCALITY: ${OWNER_LOCALITY?}
      OWNER_STATE_OR_PROVINCE: ${OWNER_STATE_OR_PROVINCE?}
      OWNER_COUNTRY_NAME: ${OWNER_COUNTRY_NAME?}
    volumes:
      - ./ssl:/ssl

  install:
    build:
      context: infrastructure/docker/install
    environment:
      PROTOCOL: ${PROTOCOL?}
      HTTP_PORT: ${HTTP_PORT?}
      HTTPS_PORT: ${HTTPS_PORT?}
      HOST: ${HOST?}
      ABS_PATH: ${ABS_PATH?}
      OWNER_CERT_PASSWORD: ${OWNER_CERT_PASSWORD?}
      ENDPOINT: ${ENDPOINT?}
    volumes:
      - ./ssl:/ssl

  processor:
    build:
      context: infrastructure/docker/processor
    environment:
      ENDPOINT: ${ENDPOINT?}
      GRAPH_STORE: ${GRAPH_STORE?}
      ONTOLOGY: ${ONTOLOGY?}
    volumes:
      - ./infrastructure/docker/processor/config/noi.ttl:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/it/bz/opendatahub/kg/noi.ttl
      - ./infrastructure/docker/processor/config/location-mapping.n3:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/custom-mapping.n3
      - ./infrastructure/docker/processor/config/content.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml

  # is it usefult for production or only for development?
  processor-nginx:
    build:
      context: infrastructure/docker/processor-nginx
    depends_on:
      - processor
    ports:
      - 8888:80
    environment:
      PROXY_PASS: http://processor:8080
      PROXY_SET_HOST: ${HOST?}

  email-server:
    image: namshi/smtp
    environment:
      DISABLE_IPV6: 'true'
  ######

  nginx:
    build:
      context: infrastructure/docker/nginx
    mem_limit: 128m
    ports:
      - ${HTTP_PORT:-1333}:${HTTP_PORT:-1333}
    environment:
      HTTP_PORT: ${HTTP_PORT:-1333}
      MAX_BODY_SIZE: 2097152

  linkeddatahub:
    build:
      context: infrastructure/docker/linkeddatahub
    environment:
      CATALINA_OPTS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75 # heap will use up to 75% of container's RAM
      TZ: Europe/Copenhagen
      PROXY_HOST: nginx
      PROXY_HTTP_PORT: 1 # nginx http port
      PROXY_HTTPS_PORT: 1 # nginx https port
      PROTOCOL: http
      HTTP_SCHEME: http
      HOST: linkeddatahub
      ABS_PATH: /
      HTTP_PORT: 8080
      HTTP_PROXY_NAME: likeddatahub
      HTTP_PROXY_PORT: 1 # https port
      HTTP_REDIRECT_PORT: 1# https port
      HTTPS_PROXY_PORT: 1 # https port
      HTTPS: 'false'
      CLIENT_KEYSTORE_PASSWORD: 1# pwd
      CLIENT_TRUSTSTORE_PASSWORD: LinkedDataHub
      SELF_SIGNED_CERT: 'true' # only on localhost
      SIGN_UP_CERT_VALIDITY: 180
      IMPORT_KEEPALIVE: 300000
      MAX_CONTENT_LENGHT: 2097152
      MAIL_SMPT_HOST: email-server
      MAIL_SMTP_PORT: 25
      MAIL_USER: lineddatahub@localhost
      OWNER_MBOX: 1 # owner mbox

volumes:
  ssl:
