version: '3.8'

services:
  setup:
    build:
      context: infrastructure/docker/setup
    environment:
      PROTOCOL: ${PROTOCOL?}
      HTTP_PORT: ${HTTP_PORT?}
      HTTPS_PORT: ${HTTPS_PORT?}
      HOST: ${HOST?}
      ABS_PATH: ${ABS_PATH?}
      OWNER_CERT_PASSWORD: ${OWNER_CERT_PASSWORD?}
      SECRETARY_CERT_PASSWORD: ${SECRETARY_CERT_PASSWORD?}
      OWNER_GIVEN_NAME: ${OWNER_GIVEN_NAME?}
      OWNER_FAMILY_NAME: ${OWNER_FAMILY_NAME?}
      OWNER_ORGANIZATION: ${OWNER_ORGANIZATION?}
      OWNER_ORG_UNIT: ${OWNER_ORG_UNIT?}
      OWNER_LOCALITY: ${OWNER_LOCALITY?}
      OWNER_STATE_OR_PROVINCE: ${OWNER_STATE_OR_PROVINCE?}
      OWNER_COUNTRY_NAME: ${OWNER_COUNTRY_NAME?}
    volumes:
      - ssl:/ssl

  install:
    build:
      context: infrastructure/docker/install
    environment:
      PROTOCOL: ${PROTOCOL?}
      HTTP_PORT: ${HTTP_PORT?}
      HTTPS_PORT: ${HTTPS_PORT?}
      HOST: ${HOST?}
      ABS_PATH: ${ABS_PATH?}
      OWNER_CERT_PASSWORD: ${OWNER_CERT_PASSWORD?}
      ENDPOINT: ${ENDPOINT?}
    volumes:
      - ssl:/ssl

  nginx:
    build:
      context: infrastructure/docker/nginx
    mem_limit: 128m
    ports:
      - ${HTTP_PORT}:8080
      - ${HTTPS_PORT}:8443
    environment:
      HTTPS_PORT: ${HTTPS_PORT?}
      UPSTREAM_SERVER: linkeddatahub
      SERVER_NAME: ${HOST?}
      SERVER_HTTPS_PORT: 8433
      SERVER_HTTP_PORT: 8080
      SERVER_CERT_FILE: /etc/nginx/ssl/server/server.crt
      SERVER_KEY_FILE: /etc/nginx/ssl/server/server.key
      MAX_BOXY_SIZE: 2097152
    volumes:
      - ssl:/etx/nginx/ssl:ro

  linkeddatahub:
    build:
      context: infrastructure/docker/linkeddatahub
      target: development
    environment:
      CATALINA_OPTS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75 # heap will use up to 75% of container's RAM
      TZ: Europe/Copenhagen
      PROXY_HOST: nginx
      PROXY_HTTP_PORT: 8080 # nginx http port
      PROXY_HTTPS_PORT: 8443 # nginx https port
      PROTOCOL: ${PROTOCOL?}
      HTTP_SCHEME: https
      HOST: ${HOST?}
      ABS_PATH: ${ABS_PATH?}
      HTTP_PORT: 7070
      HTTP_PROXY_NAME: ${HOST?}
      HTTP_PROXY_PORT: ${HTTPS_PORT?} # https port
      HTTP_REDIRECT_PORT: ${HTTPS_PORT?} # https port
      HTTPS_PROXY_PORT: ${HTTPS_PORT?} # https port
      HTTPS: 'false'
      CLIENT_KEYSTORE_PASSWORD: ${SECRETARY_CERT_PASSWORD?} # pwd
      CLIENT_TRUSTSTORE_PASSWORD: LinkedDataHub
      SELF_SIGNED_CERT: 'true' # only on localhost
      SIGN_UP_CERT_VALIDITY: 180
      IMPORT_KEEPALIVE: 300000
      MAX_CONTENT_LENGHT: 2097152
      MAIL_SMTP_HOST: email-server
      MAIL_SMTP_PORT: 25
      MAIL_USER: lineddatahub@localhost
      OWNER_MBOX: ${OWNER_MBOX?} # owner mbox
    volumes:
      - ssl:/var/linkeddatahub/ssl
      - uploads:/var/ww/linkeddatahub/uploads

  processor:
    build:
      context: infrastructure/docker/processor
    environment:
      ENDPOINT: ${ENDPOINT?}
      GRAPH_STORE: ${GRAPH_STORE?}
      ONTOLOGY: ${ONTOLOGY?}

  processor-nginx:
    build:
      context: infrastructure/docker/processor-nginx
    depends_on:
      - processor
    # only for development
    ports:
      - 8888:80
    environment:
      PROXY_PASS: http://processor:8080
      PROXY_SET_HOST: ${HOST?}

  fuseki-admin:
    build:
      context: infrastructure/docker/fuseki-admin
    user: root
    # only for development
    ports:
      - 3030:3030
    volumes:
      - admin-data:/fuseki/databases

  fuseki-end-user:
    build:
      context: infrastructure/docker/fuseki-end-user
    user: root
    # only for development
    ports:
      - 3031:3030
    volumes:
      - end-user-data:/fuseki/databases

  varnish-admin:
    build:
      context: infrastructure/docker/varnish-admin
    user: root
    depends_on:
      - linkeddatahub
    tmpfs: /var/lib/varnish:exec
    environment:
      BACKEND_HOST: fuseki-admin
      BACKEND_PORT: 3030
      CLIENT_HOST: linkeddatahub
      VARNISH_TTL: 86400
      VARNISH_SIZE: 1G

  varnish-end-user:
    build:
      context: infrastructure/docker/varnish-end-user
    user: root
    depends_on:
      - linkeddatahub
    tmpfs: /var/lib/varnish:exec
    environment:
      BACKEND_HOST: fuseki-end-user
      BACKEND_PORT: 3030
      CLIENT_HOST: linkeddatahub
      VARNISH_TTL: 86400
      VARNISH_SIZE: 1G

  email-server:
    image: namshi/smtp
    environment:
      DISABLE_IPV6: 'true'

volumes:
  ssl:
  uploads:
  admin-data:
  end-user-data:
