FROM atomgraph/processor

COPY config/noi.ttl /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/it/bz/opendatahub/kg/noi.ttl
COPY config/location-mapping.n3 /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/custom-mapping.n3
COPY config/context.xml /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml
